name: Release
on:
  push:
    tags: ["*"]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: olafurpg/setup-scala@v13
      - uses: olafurpg/setup-gpg@v3
      - uses: coursier/cache-action@v6.3
      - name: Publish
        run: |
          sbt nailgun-server/releaseEarly
        env:
          SONA_PASS: ${{ secrets.SONATYPE_PASSWORD }}
          SONA_USER: ${{ secrets.SONATYPE_USERNAME }}
